# Generated by Django 5.1.7 on 2025-03-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='description',
        ),
        migrations.AddField(
            model_name='media',
            name='user_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
