# Generated by Django 5.1.7 on 2025-03-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tokens_amount',
            field=models.IntegerField(default=0, help_text='Amount of special currency tokens'),
        ),
    ]
